# Generated by Django 4.0.6 on 2022-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='purpose',
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
