# Generated by Django 4.0.6 on 2022-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
