# Generated by Django 4.0.6 on 2022-07-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_image_delete_propertypictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='property_pics/'),
        ),
    ]
